name: amazing_python_script
channels:
  - conda-forge
  - defaults
  - pypi
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - ld_impl_linux-64=2.40
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libnsl=2.0.0
  - libsqlite=3.40.0
  - libuuid=2.38.1
  - libzlib=1.2.13
  - ncurses=6.3
  - openssl=3.1.0
  - pip=23.1.2
  - python=3.9.16
  - readline=8.2
  - setuptools=67.7.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.40.0
  - xz=5.2.6
  - pip:
      - async-generator==1.10
      - attrs==23.1.0
      - blinker==1.6.2
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - dominate==2.7.0
      - exceptiongroup==1.1.1
      - flask==2.3.1
      - flask-bootstrap==3.3.7.1
      - flask-modals==0.5.1
      - flask-wtf==1.1.1
      - google-images-download==2.8.0
      - h11==0.14.0
      - idna==3.4
      - importlib-metadata==6.6.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - outcome==1.2.0
      - pysocks==1.7.1
      - requests==2.29.0
      - selenium==4.9.0
      - simple-image-download==0.2
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - trio==0.22.0
      - trio-websocket==0.10.2
      - urllib3==1.26.15
      - visitor==0.1.3
      - werkzeug==2.3.2
      - wsproto==1.2.0
      - wtforms==3.0.1
      - zipp==3.15.0
