name: ✨ Feature Request
description: Suggest a feature request
title: '[Feat]: '
labels: ['⭐ goal: addition']
body:
- type: textarea
  id: what-feature
  attributes:
    label: Is your feature request related to a problem? Please describe.
    placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  validations:
    required: true
- type: textarea
  id: solution
  attributes:
    label: Describe the solution you'd like.
    placeholder: A clear and concise description of what you want to happen.
  validations:
    required: true  
- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered.
    placeholder: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true         
- type: textarea
  id: screenshots
  attributes:
    label: Show us the magic with screenshots
    placeholder: Attach screenshots to visualize your idea
  validations:
    required: false    
- type: checkboxes
  id: terms
  attributes:
    label: 'Record'
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
      - label: I'm a GSSoC'23 contributor
      - label: I want to work on this issue

